name: Test & Build

on:
  workflow_call:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.18 ]
    steps:
    - 
      name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - 
      name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - 
      name: Check code
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        # skip cache because of flaky behaviors
        skip-build-cache: true
        skip-pkg-cache: true
    -
      name: Run Tests
      run: go test -cover -p 1 -race -v ./...