before:
  hooks:
    - go mod tidy

builds:
   -
    id: csync
    binary: '{{ .ProjectName }}'
    main: main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
        - goos: darwin
          goarch: 386
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w

archives:
  -
    id: csync
    builds:
      - csync
    name_template: "csync_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  -
    name: csync
    ids:
      - csync
    repository: 
      owner: katallaxie
      name: homebrew-csync-tap
    folder: Formula
    goarm: "7"
    homepage: https://katallaxie.github.io/csync/
    dependencies:
      - name: go
        type: optional
    install: |-
      bin.install "csync"

release:
  ids:
    - csync
  header: |
    ## {{.Version}} Release ({{ .Date }})

    Welcome to this new release :rocket:!
  footer: |
    ## Thanks!

    Those were the changes on {{ .Tag }}!

gomod:
  proxy: true

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "csync_checksums.txt"