baseURL = ''
languageCode = 'en-us'
title = 'csync | The Cloud Sync Tool'
theme = 'hugo-whisper-theme'

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs"
    weight = 2

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[markup]
  [markup.highlight]
    style = 'vim'
    noClasses = false

[params]
  google_analytics_id=""
  homepage_button_link = 'docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'csync is a command line tool for synchronizing files to and from various cloud storage services.'

  [params.logo]
      mobile = ""
      standard  = ""