name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docs.yml'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true 
      - run: | 
          hugo --minify --baseURL=https://katallaxie.github.io/csync/
      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public